@ Player speaks to the Great Spirit
Text_BootedUpPC::
	.string "{PLAYER} keluatl kjiniskam.$"

Text_AccessWhichPC::
	.string "LIKPENIKNN pewantk pana'latl?$"

Text_AccessedSomeonesPC::
	.string "Pana'latl NA'TUENN LIKPENIKN.$"

Text_OpenedPkmnStorage::
	.string "POKéMON LIKPENIKNN pana'latl.$"

Text_AccessedPlayersPC::
	.string "Pana'latl {PLAYER} LIKPENIKNN.$"

Text_AccessedBillsPC::
	.string "Pana'latl SUL LIKPENIKNN.$"
