Text_MonSentToBoxInSomeonesPC::
    .string "{STR_VAR_2} ewjo'toqol\n"
    .string "NA'TUEN LIKPENIKNN.\p"
    .string "Tepo'tas'k\n"
    .string "LIKPENIKN “{STR_VAR_1}.”$"

Text_MonSentToBoxInBillsPC::
    .string "{STR_VAR_2} ewjo'toqol\n"
    .string "SUL LIKPENIKNN.\p"
    .string "Tepo'tas'k\n"
    .string "LIKPENIKN “{STR_VAR_1}.”$"

Text_MonSentToBoxSomeonesBoxFull::
    .string "LIKPENIKN “{STR_VAR_3}”\n"
    .string "NA'TUEN LIKPENIKNN waju'aql.\p"
    .string "{STR_VAR_2} ewjo'toqol\n"
    .string "LIKPENIKN “{STR_VAR_1}.”$"

Text_MonSentToBoxBillsBoxFull::
    .string "LIKPENIKN “{STR_VAR_3}”\n"
    .string "SUL LIKPENIKNN waju'aql.\p"
    .string "{STR_VAR_2} ewjo'toqol\n"
    .string "LIKPENIKN “{STR_VAR_1}.”$"

Text_PlayerObtainedTheMon::
    .string "{PLAYER} mesn'k\n"
    .string "{STR_VAR_1}!$"

@ Unused. Translated below
@ You cannot carry any more Pokemon, so {STR_VAR_2} was sent to PC Box {STR_VAR_1}!
Text_MonSentToBoxInPC::
    .string "ポケモンを　もちきれないので\n"
    .string "パソコンの　ボックス“{STR_VAR_1}”　に\l"
    .string "{STR_VAR_2}を　てんそうした！$"

Text_NoMoreRoomForPokemon::
    .string "Moqwa' me' POKéMON!\p"
    .string "POKéMON LIKPENIKNN waju'aql!$"
