Text_MayIHelpYou::
	.string "Kwe'!\n"
	.string "Apoqonmul?$"

Text_FillOutQuestionnaire::
	.string "There is a questionnaire.\n"
	.string "Would you like to fill it out?$"

Text_QuestionnaireThankYou::
	.string "Wela'lin for taking the time to\n"
	.string "fill out our questionnaire.\p"
	.string "Your feedback will be used for\n"
	.string "future reference.$"

Text_YouKnowThoseWords::
	.string "O, kwe'!\n"
	.string "Ki'l keitoq klusuaqann?\p"
	.string "To'q ki'l keitoq\n"
	.string "MYSTERY GIFT.\p"
	.string "Weja'tekemk, ki'l mesn'k\n"
	.string "MYSTERY GIFTS!$"

Text_YouCanAccessMysteryGift::
	.string "Ta'n ki'l ewi'k'k,\n"
	.string "mesn'k MYSTERY GIFT.$"

Text_ThankYouForAccessingMysteryGift::
	.string "Wela'lin neiapt'k\n"
	.string "MYSTERY GIFT System.$"
