gText_WouldYouLikeToSaveTheGame::
	.string "Ewi'kiket laskukwaqan?$"

gText_AlreadySaveFile_WouldLikeToOverwrite::
	.string "Laskukwaqan ewi'k'k ki's.\n"
	.string "Ewi'kiket app?$"

gText_SavingDontTurnOffThePower::
	.string "EWI'KIKET…\n"
	.string "MOQWA' NAQASUA'TOQ!$"

gText_PlayerSavedTheGame::
	.string "{PLAYER} ewi'kiket laskukwaqan.$"

gText_SaveFailed2::
	.string "セーブに　しっぱい　しました‥$"

gText_DifferentGameFile::
	.string "JIPALATL!\p"
	.string "Istue'k laskukwaqan\n"
	.string "ewi'k'k ki's.\p"
	.string "Ewi'kiket nike', kisanatl istue'k\n"
	.string "laskukwaqan. Papitaqann aq\l"
	.string "POKéMON kisnatl iapjiw.\p"
	.string "Ewi'kiket nike'\n"
	.string "aq kisanatl istue'k laskukwaqan?$"
