@ For the NPC in Pallet Town that talks about the Trainer Tips sign

PalletTown_Text_HmmIsThatRight::
	.string "Quq…\n"
	.string "Toqo na…$"

PalletTown_Text_OhLookLook::
	.string "O!\n"
	.string "Ankapt'k, ankapt'k!$"

PalletTown_Text_ReadItReadIt::
	.string "Ekiljet, ekiljet!$"

@ Used by sign
PalletTown_Text_PressStartToOpenMenu::
	.string "KEKNUIMATL\p"
	.string "Esna'toq (START) pana'latl ELQWANIK!$"

PalletTown_Text_SignsAreUsefulArentThey::
	.string "Wi'katiknn uktapsunikl, na to'q?$"

PalletTown_Text_LookCopiedTrainerTipsSign::
	.string "Ankapt'k, ankapt'k!\p"
	.string "Napkwetu klusuaqann weket\n"
	.string "KEKNUIMATL wi'katiknn!$"

@ Used by NPC
PalletTown_Text_PressStartToOpenMenuCopy::
	.string "KEKNUIMATL!\p"
	.string "Esna'toq (START) pana'latl ELQWANIK!$"
